spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-174-129-252-211.compute-1.amazonaws.com:5432/d47eh832am0qgj
    username: dpnuedcczvevsy
    password: 1f60b24a2217424575a237acc4ef05427b2eacbeeeedf86b4507f1940774097d
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false

management:
  endpoints:
    web:
      cors:
        allowed-origins: https://dry-wave-98792.herokuapp.com
        allowed-methods: GET,POST